//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:\Github Repos\GameLab-RnD\Compiler\StoryGrammar.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="StoryGrammar"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IStoryGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="StoryGrammar.story"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStory([NotNull] StoryGrammar.StoryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StoryGrammar.story"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStory([NotNull] StoryGrammar.StoryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StoryGrammar.story_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStory_part([NotNull] StoryGrammar.Story_partContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StoryGrammar.story_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStory_part([NotNull] StoryGrammar.Story_partContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StoryGrammar.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterText([NotNull] StoryGrammar.TextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StoryGrammar.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitText([NotNull] StoryGrammar.TextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StoryGrammar.embedded_variable_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmbedded_variable_declaration([NotNull] StoryGrammar.Embedded_variable_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StoryGrammar.embedded_variable_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmbedded_variable_declaration([NotNull] StoryGrammar.Embedded_variable_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StoryGrammar.embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmbedded_statement([NotNull] StoryGrammar.Embedded_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StoryGrammar.embedded_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmbedded_statement([NotNull] StoryGrammar.Embedded_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StoryGrammar.import_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImport_statement([NotNull] StoryGrammar.Import_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StoryGrammar.import_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImport_statement([NotNull] StoryGrammar.Import_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StoryGrammar.story_line_termination"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStory_line_termination([NotNull] StoryGrammar.Story_line_terminationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StoryGrammar.story_line_termination"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStory_line_termination([NotNull] StoryGrammar.Story_line_terminationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StoryGrammar.string_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_literal([NotNull] StoryGrammar.String_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StoryGrammar.string_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_literal([NotNull] StoryGrammar.String_literalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StoryGrammar.string_literal_content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString_literal_content([NotNull] StoryGrammar.String_literal_contentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StoryGrammar.string_literal_content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString_literal_content([NotNull] StoryGrammar.String_literal_contentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StoryGrammar.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] StoryGrammar.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StoryGrammar.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] StoryGrammar.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="StoryGrammar.end_of_file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnd_of_file([NotNull] StoryGrammar.End_of_fileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StoryGrammar.end_of_file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnd_of_file([NotNull] StoryGrammar.End_of_fileContext context);
}
