//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:\Github Repos\GameLab-RnD\Compiler\StoryGrammar.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IStoryGrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class StoryGrammarBaseListener : IStoryGrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="StoryGrammar.story"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStory([NotNull] StoryGrammar.StoryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StoryGrammar.story"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStory([NotNull] StoryGrammar.StoryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StoryGrammar.story_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStory_part([NotNull] StoryGrammar.Story_partContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StoryGrammar.story_part"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStory_part([NotNull] StoryGrammar.Story_partContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StoryGrammar.text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterText([NotNull] StoryGrammar.TextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StoryGrammar.text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitText([NotNull] StoryGrammar.TextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StoryGrammar.embedded_variable_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmbedded_variable_declaration([NotNull] StoryGrammar.Embedded_variable_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StoryGrammar.embedded_variable_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmbedded_variable_declaration([NotNull] StoryGrammar.Embedded_variable_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StoryGrammar.embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmbedded_statement([NotNull] StoryGrammar.Embedded_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StoryGrammar.embedded_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmbedded_statement([NotNull] StoryGrammar.Embedded_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StoryGrammar.import_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImport_statement([NotNull] StoryGrammar.Import_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StoryGrammar.import_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImport_statement([NotNull] StoryGrammar.Import_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StoryGrammar.story_line_termination"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStory_line_termination([NotNull] StoryGrammar.Story_line_terminationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StoryGrammar.story_line_termination"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStory_line_termination([NotNull] StoryGrammar.Story_line_terminationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StoryGrammar.string_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_literal([NotNull] StoryGrammar.String_literalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StoryGrammar.string_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_literal([NotNull] StoryGrammar.String_literalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StoryGrammar.string_literal_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString_literal_content([NotNull] StoryGrammar.String_literal_contentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StoryGrammar.string_literal_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString_literal_content([NotNull] StoryGrammar.String_literal_contentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StoryGrammar.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] StoryGrammar.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StoryGrammar.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] StoryGrammar.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="StoryGrammar.end_of_file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnd_of_file([NotNull] StoryGrammar.End_of_fileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StoryGrammar.end_of_file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnd_of_file([NotNull] StoryGrammar.End_of_fileContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
